### ISSUE TITLE
Issue saving a lock while background save is going

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/Challenges#96]
```
13:38:08 [INFO] Leonheart515 issued server command: /mchest
13:38:08 [INFO] [WorldGuard] Region data changes made in 'world' have been background saved
13:38:08 [WARN] com.sk89q.worldguard.protection.managers.storage.StorageException: Failed to rename temporary regions file to /home/flatcore/season4/plugins/WorldGuard/worlds/world/regions.yml
13:38:08 [WARN]         at com.sk89q.worldguard.protection.managers.storage.file.YamlRegionFile.saveAll(YamlRegionFile.java:249)
13:38:08 [WARN]         at com.sk89q.worldguard.protection.managers.RegionManager.save(RegionManager.java:109)
13:38:08 [WARN]         at us.corenetwork.challenges.WorldGuardManager.createRegion(WorldGuardManager.java:41)
13:38:08 [WARN]         at us.corenetwork.challenges.modcommands.LockCommand.run(LockCommand.java:123)
13:38:08 [WARN]         at us.corenetwork.challenges.modcommands.BaseModCommand.execute(BaseModCommand.java:42)
13:38:08 [WARN]         at us.corenetwork.challenges.Challenges.onCommand(Challenges.java:200)
13:38:08 [WARN]         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
13:38:08 [WARN]         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
13:38:08 [WARN]         at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645)
13:38:08 [WARN]         at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:575)
13:38:08 [WARN]         at us.corenetwork.core.alias.actions.RunCommandAction.execute(RunCommandAction.java:29)
13:38:08 [WARN]         at us.corenetwork.core.alias.CommandAlias.execute(CommandAlias.java:65)
13:38:08 [WARN]         at us.corenetwork.core.alias.AliasModule.onCommand(AliasModule.java:61)
13:38:08 [WARN]         at us.corenetwork.core.alias.AliasModule.onCommandEntered(AliasModule.java:55)
13:38:08 [WARN]         at sun.reflect.GeneratedMethodAccessor181.invoke(Unknown Source)
13:38:08 [WARN]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:38:08 [WARN]         at java.lang.reflect.Method.invoke(Method.java:483)
13:38:08 [WARN]         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
13:38:08 [WARN]         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
13:38:08 [WARN]         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
13:38:08 [WARN]         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
13:38:08 [WARN]         at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1107)
13:38:08 [WARN]         at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
13:38:08 [WARN]         at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
13:38:08 [WARN]         at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
13:38:08 [WARN]         at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
13:38:08 [WARN]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
13:38:08 [WARN]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
13:38:08 [WARN]         at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683)
13:38:08 [WARN]         at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
13:38:08 [WARN]         at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
13:38:08 [WARN]         at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
13:38:08 [WARN]         at java.lang.Thread.run(Thread.java:745)
```

**Comment by riddle** [comment]
Couldn’t reproduce in ages, closing.
