### ISSUE TITLE
Negative points don’t work

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/Challenges#97]
Player had 69 points and 1 pending.

```
03:22:39 [INFO] ridddle issued server command: /chm points unorfc -70 Resetting the rank to Novice as the account owner changed (requested by them)
03:22:39 [ERROR] null
org.bukkit.command.CommandException: Unhandled exception executing command 'chm' in plugin Challenges v1.0.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8-dev.jar:git-Spigot-59b08be-0899683]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8-dev.jar:git-Spigot-59b08be-0899683]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.8-dev.jar:git-Spigot-59b08be-0899683]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot-1.8-dev.jar:git-Spigot-59b08be-0899683]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot-1.8-dev.jar:git-Spigot-59b08be-0899683]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-1.8-dev.jar:git-Spigot-59b08be-0899683]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot-1.8-dev.jar:git-Spigot-59b08be-0899683]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8-dev.jar:git-Spigot-59b08be-0899683]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot-1.8-dev.jar:git-Spigot-59b08be-0899683]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8-dev.jar:git-Spigot-59b08be-0899683]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8-dev.jar:git-Spigot-59b08be-0899683]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8-dev.jar:git-Spigot-59b08be-0899683]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
        at us.corenetwork.challenges.modcommands.ModPointsCommand.modifyPoints(ModPointsCommand.java:49) ~[?:?]
        at us.corenetwork.challenges.modcommands.ModPointsCommand.run(ModPointsCommand.java:37) ~[?:?]
        at us.corenetwork.challenges.modcommands.BaseModCommand.execute(BaseModCommand.java:42) ~[?:?]
        at us.corenetwork.challenges.Challenges.onCommand(Challenges.java:200) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8-dev.jar:git-Spigot-59b08be-0899683]
        ... 14 more
```

Still the same for them. I need this fixed to unban them as the original account owner wants to use the account. That’s why I set high priority.

**Comment by narrowtux** [comment]
The NPE is thrown because the player's data file is missing. Not because
you use negative points. I'll fix that anyway.

Piotr <notifications@github.com> schrieb am Thu Jan 08 2015 at 9:24:00 AM:
