### ISSUE TITLE
/chm list <Player> is broken

### ISSUE THREAD

**Issue by riddle** [CoreNetwork/Challenges#98]
```
05:48:50 [INFO] <-F> lubkin: if someone brings a horse to you and givespet you can get on and get out
05:48:53 [INFO] ridddle issued server command: /chm list Leonheart515
05:48:53 [ERROR] null
org.bukkit.command.CommandException: Unhandled exception executing command 'chm' in plugin Challenges v1.0.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8-dev.jar:git-Spigot-7297fbd-8047b0a]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8-dev.jar:git-Spigot-7297fbd-8047b0a]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.8-dev.jar:git-Spigot-7297fbd-8047b0a]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [spigot-1.8-dev.jar:git-Spigot-7297fbd-8047b0a]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [spigot-1.8-dev.jar:git-Spigot-7297fbd-8047b0a]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [spigot-1.8-dev.jar:git-Spigot-7297fbd-8047b0a]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [spigot-1.8-dev.jar:git-Spigot-7297fbd-8047b0a]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot-1.8-dev.jar:git-Spigot-7297fbd-8047b0a]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot-1.8-dev.jar:git-Spigot-7297fbd-8047b0a]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8-dev.jar:git-Spigot-7297fbd-8047b0a]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8-dev.jar:git-Spigot-7297fbd-8047b0a]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8-dev.jar:git-Spigot-7297fbd-8047b0a]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: Leonheart515
        at java.util.UUID.fromString(UUID.java:194) ~[?:1.8.0_25]
        at us.corenetwork.challenges.Util.getUUIDFromString(Util.java:222) ~[?:?]
        at us.corenetwork.challenges.modcommands.CompletedListCommand.sendAllPlayer(CompletedListCommand.java:155) ~[?:?]
        at us.corenetwork.challenges.modcommands.CompletedListCommand.run(CompletedListCommand.java:31) ~[?:?]
        at us.corenetwork.challenges.modcommands.BaseModCommand.execute(BaseModCommand.java:42) ~[?:?]
        at us.corenetwork.challenges.Challenges.onCommand(Challenges.java:200) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8-dev.jar:git-Spigot-7297fbd-8047b0a]
        ... 14 more
```

UUID stuff again? :)

**Comment by narrowtux** [comment]
Turns out I used the wrong convert method. Luckily nothing wrong with the database.
